-- PARTE 1
CREATE TABLESPACE mid_term DATAFILE 
'df_mid_term.dbf' SIZE 50M;

CREATE USER rbrand
IDENTIFIED BY rbrand
DEFAULT TABLESPACE mid_term
QUOTA UNLIMITED ON mid_term;

CREATE ROLE MINI_DBA;
GRANT CREATE SEQUENCE, CREATE TABLE TO MINI_DBA;

CREATE ROLE STUDENT;
GRANT connect, MINI_DBA TO STUDENT;

GRANT STUDENT TO rbrand;

-- PARTE 2
CREATE SEQUENCE MUNICIPIOS_SEQ MAXVALUE 100 INCREMENT BY 1 START WITH 10;
CREATE SEQUENCE CAPTURAS_SEQ MAXVALUE 6000 INCREMENT BY 1 START WITH 5000;

CREATE TABLE MUNICIPIOS
( ID INTEGER, 
NOMBRE VARCHAR(256),
CONSTRAINT municipios_pk PRIMARY KEY (ID)
);

INSERT INTO municipios (id, nombre) VALUES (MUNICIPIOS_SEQ.NEXTVAL, 'ANDES');
INSERT INTO municipios (id, nombre) VALUES (MUNICIPIOS_SEQ.NEXTVAL, 'APARTADÓ');
INSERT INTO municipios (id, nombre) VALUES (MUNICIPIOS_SEQ.NEXTVAL, 'ARAUCA (CT)');
INSERT INTO municipios (id, nombre) VALUES (MUNICIPIOS_SEQ.NEXTVAL, 'BARBOSA');
INSERT INTO municipios (id, nombre) VALUES (MUNICIPIOS_SEQ.NEXTVAL, 'BELLO');
INSERT INTO municipios (id, nombre) VALUES (MUNICIPIOS_SEQ.NEXTVAL, 'CAUCASIA');
INSERT INTO municipios (id, nombre) VALUES (MUNICIPIOS_SEQ.NEXTVAL, 'CIUDAD BOLÍVAR');
INSERT INTO municipios (id, nombre) VALUES (MUNICIPIOS_SEQ.NEXTVAL, 'DON MATÍAS');
INSERT INTO municipios (id, nombre) VALUES (MUNICIPIOS_SEQ.NEXTVAL, 'ITUANGO');
INSERT INTO municipios (id, nombre) VALUES (MUNICIPIOS_SEQ.NEXTVAL, 'JARDÍN');
INSERT INTO municipios (id, nombre) VALUES (MUNICIPIOS_SEQ.NEXTVAL, 'LA CEJA');
INSERT INTO municipios (id, nombre) VALUES (MUNICIPIOS_SEQ.NEXTVAL, 'LETICIA (CT)');
INSERT INTO municipios (id, nombre) VALUES (MUNICIPIOS_SEQ.NEXTVAL, 'MEDELLÍN (CT)');
INSERT INTO municipios (id, nombre) VALUES (MUNICIPIOS_SEQ.NEXTVAL, 'RIONEGRO');
INSERT INTO municipios (id, nombre) VALUES (MUNICIPIOS_SEQ.NEXTVAL, 'SALGAR');
INSERT INTO municipios (id, nombre) VALUES (MUNICIPIOS_SEQ.NEXTVAL, 'SANTAFÉ DE ANTIOQUIA');
INSERT INTO municipios (id, nombre) VALUES (MUNICIPIOS_SEQ.NEXTVAL, 'VALDIVIA');

CREATE TABLE CAPTURAS 
(ID INTEGER, 
FECHA DATE, 
DEPARTAMENTO VARCHAR(255), 
MUNICIPIO_ID INTEGER, 
DIA VARCHAR(255), 
BARRIO VARCHAR(255), 
ZONA VARCHAR(255), 
CLASE_SITIO VARCHAR(255), 
EDAD INTEGER, 
SEXO VARCHAR(255), 
ESTADO_CIVIL VARCHAR(255),
CLASE_EMPLEADO VARCHAR(255), 
PROFESION VARCHAR(255), 
ESCOLARIDAD VARCHAR(255), 
DELITO VARCHAR(255),
CONSTRAINT capturas_pk PRIMARY KEY (ID),
CONSTRAINT fk_municipio_id FOREIGN KEY (MUNICIPIO_ID) REFERENCES municipios(ID)
);


REM INSERTING into RBRAND.CAPTURAS
SET DEFINE OFF;
Insert into RBRAND.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO_ID,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO) values ('5000',to_date('01/01/18','DD/MM/RR'),'AMAZONAS','22','Lunes','AGUILA','URBANA','VIAS PUBLICAS','20','MASCULINO','SOLTERO','EMPLEADO PARTICULAR','0','0','ARTÍCULO 376. TRÁFICO, FABRICACIÓN O PORTE DE ESTUPEFACIENTES');
Insert into RBRAND.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO_ID,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO) values ('5001',to_date('01/01/18','DD/MM/RR'),'AMAZONAS','22','Lunes','ESPERANZA','URBANA','VIAS PUBLICAS','21','MASCULINO','SOLTERO','EMPLEADO PARTICULAR','0','0','ARTÍCULO 103. HOMICIDIO');
Insert into RBRAND.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO_ID,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO) values ('5002',to_date('01/01/18','DD/MM/RR'),'AMAZONAS','22','Lunes','SIMON BOLIVAR','URBANA','VIAS PUBLICAS','23','MASCULINO','UNION LIBRE','EMPLEADO PARTICULAR','0','0','ARTÍCULO 111. LESIONES PERSONALES');
Insert into RBRAND.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO_ID,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO) values ('5003',to_date('01/01/18','DD/MM/RR'),'ANTIOQUIA','11','Lunes','PARQUE PRINCIPAL','RURAL','VIAS PUBLICAS','45','MASCULINO','CASADO','AGRICULTOR','0','0','ARTÍCULO 429. VIOLENCIA CONTRA SERVIDOR PÚBLICO');
Insert into RBRAND.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO_ID,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO) values ('5004',to_date('01/01/18','DD/MM/RR'),'ANTIOQUIA','12','Lunes','EL AMPARO','URBANA','VIAS PUBLICAS','31','MASCULINO','SOLTERO','EMPLEADO PARTICULAR','0','0','ARTÍCULO 239. HURTO ENTIDADES COMERCIALES');
Insert into RBRAND.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO_ID,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO) values ('5005',to_date('01/01/18','DD/MM/RR'),'ANTIOQUIA','12','Lunes','EL AMPARO','URBANA','VIAS PUBLICAS','37','MASCULINO','SOLTERO','EMPLEADO PARTICULAR','0','0','ARTÍCULO 239. HURTO ENTIDADES COMERCIALES');
Insert into RBRAND.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO_ID,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO) values ('5006',to_date('01/01/18','DD/MM/RR'),'ANTIOQUIA','14','Lunes','ROBLES','URBANA','VIAS PUBLICAS','50','MASCULINO','SOLTERO','INDEPENDIENTE','0','0','ARTÍCULO 111. LESIONES PERSONALES');
Insert into RBRAND.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO_ID,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO) values ('5007',to_date('01/01/18','DD/MM/RR'),'ANTIOQUIA','15','Lunes','VDA. POTRERITO','RURAL','VIAS PUBLICAS','18','MASCULINO','SOLTERO','INDEPENDIENTE','0','0','ARTÍCULO 376. TRÁFICO, FABRICACIÓN O PORTE DE ESTUPEFACIENTES');
Insert into RBRAND.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO_ID,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO) values ('5008',to_date('01/01/18','DD/MM/RR'),'ANTIOQUIA','16','Lunes','PARQUE PRINCIPAL','URBANA','VIAS PUBLICAS','46','FEMENINO','UNION LIBRE','AMA DE CASA','0','0','ARTÍCULO 111. LESIONES PERSONALES');
Insert into RBRAND.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO_ID,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO) values ('5009',to_date('01/01/18','DD/MM/RR'),'ANTIOQUIA','16','Lunes','EL BOSQUE','URBANA','TRAMO DE VIA','32','MASCULINO','SOLTERO','INDEPENDIENTE','0','0','ARTÍCULO 111. LESIONES PERSONALES');
Insert into RBRAND.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO_ID,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO) values ('5010',to_date('01/01/18','DD/MM/RR'),'ANTIOQUIA','17','Lunes','PIO XII','URBANA','VIAS PUBLICAS','37','MASCULINO','SOLTERO','INDEPENDIENTE','0','0','ARTÍCULO 429. VIOLENCIA CONTRA SERVIDOR PÚBLICO');
Insert into RBRAND.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO_ID,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO) values ('5011',to_date('01/01/18','DD/MM/RR'),'ANTIOQUIA','18','Lunes','RIO GRANDE','RURAL','VIAS PUBLICAS','25','MASCULINO','SOLTERO','INDEPENDIENTE','0','0','ARTÍCULO 239. HURTO PERSONAS');
Insert into RBRAND.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO_ID,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO) values ('5012',to_date('01/01/18','DD/MM/RR'),'ANTIOQUIA','19','Lunes','PARQUE PRINCIPAL','URBANA','VIAS PUBLICAS','24','MASCULINO','SOLTERO','INDEPENDIENTE','0','0','ARTÍCULO 429. VIOLENCIA CONTRA SERVIDOR PÚBLICO');
Insert into RBRAND.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO_ID,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO) values ('5013',to_date('01/01/18','DD/MM/RR'),'ANTIOQUIA','20','Lunes','GUAYAQUIL','URBANA','VIAS PUBLICAS','24','MASCULINO','UNION LIBRE','INDEPENDIENTE','0','0','ARTÍCULO 111. LESIONES PERSONALES');
Insert into RBRAND.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO_ID,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO) values ('5014',to_date('01/01/18','DD/MM/RR'),'ANTIOQUIA','21','Lunes','SAN CAYETANO','URBANA','VIAS PUBLICAS','28','MASCULINO','SOLTERO','DESEMPLEADO','0','0','ARTÍCULO 376. TRÁFICO, FABRICACIÓN O PORTE DE ESTUPEFACIENTES');
Insert into RBRAND.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO_ID,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO) values ('5015',to_date('01/01/18','DD/MM/RR'),'ANTIOQUIA','23','Lunes','BUENOS AIRES  C-9','URBANA','CASAS DE HABITACION','15','MASCULINO','SOLTERO','ESTUDIANTE','0','0','ARTÍCULO 229. VIOLENCIA INTRAFAMILIAR');
Insert into RBRAND.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO_ID,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO) values ('5016',to_date('01/01/18','DD/MM/RR'),'ANTIOQUIA','23','Lunes','PEDREGAL C-6','URBANA','VIAS PUBLICAS','26','MASCULINO','CASADO','INDEPENDIENTE','0','0','ARTÍCULO 376. TRÁFICO, FABRICACIÓN O PORTE DE ESTUPEFACIENTES');
Insert into RBRAND.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO_ID,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO) values ('5017',to_date('01/01/18','DD/MM/RR'),'ANTIOQUIA','23','Lunes','ESTACION VILLA C-10','URBANA','VIAS PUBLICAS','26','MASCULINO','SOLTERO','DESEMPLEADO','0','0','ARTÍCULO 111. LESIONES PERSONALES');
Insert into RBRAND.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO_ID,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO) values ('5018',to_date('01/01/18','DD/MM/RR'),'ANTIOQUIA','23','Lunes','CAMPO VALDES 2 C-3','URBANA','VIAS PUBLICAS','58','MASCULINO','UNION LIBRE','INDEPENDIENTE','0','0','ARTÍCULO 209. ACTOS SEXUALES CON MENOR DE 14 AÑOS');
Insert into RBRAND.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO_ID,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO) values ('5019',to_date('01/01/18','DD/MM/RR'),'ANTIOQUIA','23','Lunes','CAMPO VALDES 2 C-3','URBANA','VIAS PUBLICAS','17','MASCULINO','SOLTERO','ESTUDIANTE','0','0','ARTÍCULO 365. FABRICACIÓN, TRÁFICO, PORTE O TENENCIA DE ARMAS DE FUEGO,ACCESORIOS, PARTES O MUNICIONES');
Insert into RBRAND.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO_ID,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO) values ('5020',to_date('01/01/18','DD/MM/RR'),'ANTIOQUIA','23','Lunes','TRINIDAD C-15','URBANA','VIAS PUBLICAS','15','MASCULINO','SOLTERO','INDEPENDIENTE','0','0','ARTÍCULO 376. TRÁFICO, FABRICACIÓN O PORTE DE ESTUPEFACIENTES');
Insert into RBRAND.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO_ID,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO) values ('5021',to_date('01/01/18','DD/MM/RR'),'ANTIOQUIA','23','Lunes','PALENQUE 1 C-7','URBANA','VIAS PUBLICAS','25','MASCULINO','SOLTERO','INDEPENDIENTE','0','0','ARTÍCULO 376. TRÁFICO, FABRICACIÓN O PORTE DE ESTUPEFACIENTES');
Insert into RBRAND.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO_ID,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO) values ('5022',to_date('01/01/18','DD/MM/RR'),'ANTIOQUIA','23','Lunes','TRINIDAD C-15','URBANA','VIAS PUBLICAS','20','MASCULINO','SOLTERO','EMPLEADO PARTICULAR','0','0','ARTÍCULO 239. HURTO PERSONAS');
Insert into RBRAND.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO_ID,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO) values ('5023',to_date('01/01/18','DD/MM/RR'),'ANTIOQUIA','23','Lunes','TRINIDAD C-15','URBANA','VIAS PUBLICAS','24','MASCULINO','SOLTERO','EMPLEADO PARTICULAR','0','0','ARTÍCULO 239. HURTO PERSONAS');
Insert into RBRAND.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO_ID,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO) values ('5024',to_date('01/01/18','DD/MM/RR'),'ANTIOQUIA','23','Lunes','SANTO DOMINGO  1 C-1','URBANA','VIAS PUBLICAS','42','MASCULINO','SOLTERO','INDEPENDIENTE','0','0','ARTÍCULO 180. DESPLAZAMIENTO FORZADO');
Insert into RBRAND.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO_ID,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO) values ('5025',to_date('01/01/18','DD/MM/RR'),'ANTIOQUIA','24','Lunes','AEROPUERTO','RURAL','AEROPUERTO','42','MASCULINO','SOLTERO','EMPLEADO PARTICULAR','0','0','ARTÍCULO 287. FALSEDAD MATERIAL EN DOCUMENTO PÚBLICO');
Insert into RBRAND.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO_ID,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO) values ('5026',to_date('01/01/18','DD/MM/RR'),'ANTIOQUIA','25','Lunes','LA CHUCHITA','RURAL','VIAS PUBLICAS','33','MASCULINO','SOLTERO','INDEPENDIENTE','0','0','ARTÍCULO 209. ACTOS SEXUALES CON MENOR DE 14 AÑOS');
Insert into RBRAND.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO_ID,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO) values ('5027',to_date('01/01/18','DD/MM/RR'),'ANTIOQUIA','26','Lunes','QUEBRADA SECA','RURAL','VIAS PUBLICAS','49','MASCULINO','UNION LIBRE','AGRICULTOR','0','0','ARTÍCULO 229. VIOLENCIA INTRAFAMILIAR');
Insert into RBRAND.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO_ID,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO) values ('5028',to_date('01/01/18','DD/MM/RR'),'ANTIOQUIA','27','Lunes','PARQUE PRINCIPAL','URBANA','VIAS PUBLICAS','19','MASCULINO','UNION LIBRE','INDEPENDIENTE','0','0','ARTÍCULO 429. VIOLENCIA CONTRA SERVIDOR PÚBLICO');
Insert into RBRAND.CAPTURAS (ID,FECHA,DEPARTAMENTO,MUNICIPIO_ID,DIA,BARRIO,ZONA,CLASE_SITIO,EDAD,SEXO,ESTADO_CIVIL,CLASE_EMPLEADO,PROFESION,ESCOLARIDAD,DELITO) values ('5029',to_date('01/01/18','DD/MM/RR'),'ARAUCA','13','Lunes','LAS AMERICAS','URBANA','CASAS DE HABITACION','34','MASCULINO','SOLTERO','EMPLEADO PARTICULAR','0','0','ARTÍCULO 206. ACTO SEXUAL VIOLENTO');
